erDiagram
  "RefreshToken" {
    String id "🗝️"
    String token
    String userId
    String ip "❓"
    String userAgent "❓"
    Boolean revoked
    DateTime createdAt
    DateTime expiresAt
    DateTime updatedAt
  }