erDiagram
  "User" {
    String id "🗝️"
    String email
    String name
    String password
    SiteRole siteRole
    Boolean isEmailVerified
    String emailVerificationCode "❓"
    DateTime emailVerificationExpiresAt "❓"
    String resetPasswordToken "❓"
    DateTime resetPasswordExpiresAt "❓"
    Int locationId "❓"
    String stripeCustomerId "❓"
    DateTime createdAt
    DateTime updatedAt
  }